### ISSUE TITLE
Assertion error in write_merge

### ISSUE THREAD

**Issue by ivissani** [WoLpH/pyExcelerator#1]
At line 82 in Cell.py you have the following assertion

`assert col1 < col2, '%d < %d is false'%(col1, col2)`

but the correct assertion would be

`assert col1 <= col2, '%d <= %d is false'%(col1, col2)`

since one may want to merge several rows on a single column.

**Comment by wolph** [comment]
Looks like you're right :)

I've updated the code but unfortunately I don't have access to the pypi builds for this project.
You can download the code from this repo and documentation can be found here: http://pyexcelerator.readthedocs.org/en/latest/

**Comment by ivissani** [comment]
Great, thanks!

On Tue, Jul 14, 2015 at 11:53 AM, Rick van Hattem notifications@github.com
wrote:

> Looks like you're right :)
> 
> I've updated the code but unfortunately I don't have access to the pypi
> builds for this project.
> You can download the code from this repo and documentation can be found
> here: http://pyexcelerator.readthedocs.org/en/latest/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WoLpH/pyExcelerator/issues/1#issuecomment-121267428.

## 

Ignacio Vissani
ivissani@gmail.com
