### ISSUE TITLE
生成Excel后数据的格式有问题

### ISSUE THREAD

**Issue by H-huihui** [WoLpH/pyExcelerator#3]
在遇到长数字，保存为Excel后会变为科学计数法，日期会变成 42758 这种格式，有无方法可以避免？

**Comment by wolph** [comment]
My guess would be that it can be arranged through the `NumberFormatRecord`: http://pyexcelerator.readthedocs.io/en/latest/pyExcelerator.html#pyExcelerator.BIFFRecords.NumberFormatRecord

But I honestly have no idea. I simply added this project to github and generated the docs, I'm not the original author and know very little about the internals of Excel.
